"""initial schema

Revision ID: c2a2b2ebafe3
Revises: 
Create Date: 2026-09-16 03:34:02.125623
"""
from alembic import op
import sqlalchemy as sa


revision = 'c2a2b2ebafe3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_lead_minutes', sa.Integer(), nullable=False),
    sa.Column('match_window_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confirmed_collabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_at_utc', sa.DateTime(), nullable=False),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('cached_role', sa.Enum('ENTITY', 'RESEARCHER', 'STAFF', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    op.create_table('availability_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('override_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('NO', 'MAYBE', 'YES', name='status'), nullable=False),
    sa.Column('window_start', sa.Time(), nullable=False),
    sa.Column('window_end', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'override_date', name='uq_override_user_date')
    )
    op.create_index(op.f('ix_availability_overrides_user_id'), 'availability_overrides', ['user_id'], unique=False)
    op.create_table('collab_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collab_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collab_id'], ['confirmed_collabs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collab_participants_collab_id'), 'collab_participants', ['collab_id'], unique=False)
    op.create_index(op.f('ix_collab_participants_user_id'), 'collab_participants', ['user_id'], unique=False)
    op.create_table('recurring_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('recurrence', sa.Enum('WEEKLY', 'BIWEEKLY', name='recurrence'), nullable=False),
    sa.Column('anchor_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('NO', 'MAYBE', 'YES', name='status'), nullable=False),
    sa.Column('window_start', sa.Time(), nullable=False),
    sa.Column('window_end', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_availability_user_id'), 'recurring_availability', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_availability_user_id'), table_name='recurring_availability')
    op.drop_table('recurring_availability')
    op.drop_index(op.f('ix_collab_participants_user_id'), table_name='collab_participants')
    op.drop_index(op.f('ix_collab_participants_collab_id'), table_name='collab_participants')
    op.drop_table('collab_participants')
    op.drop_index(op.f('ix_availability_overrides_user_id'), table_name='availability_overrides')
    op.drop_table('availability_overrides')
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('confirmed_collabs')
    op.drop_table('bot_settings')
    # ### end Alembic commands ###
